### ISSUE TITLE
What is the license? 

### ISSUE THREAD

**Issue by DrAlta** [yoanlcq/boulette-physiques#1]
What license does the project use?  I can't find any mention of copyrights anywhere.

**Comment by yoanlcq** [comment]
Thanks for asking! Neglecting to add licenses is a bad habit of mine, but in this particular case, boulette-physiques is more like a school assignment and I guess I don't mind what anyone does with it.  
So, feel free to grab the code and do whatever you want with it!

That being said, while it was _intended_ as a library, I don't think it is particularly good at it and wouldn't recommend direct use of it in production code. It _might_ be good as a reference for the underlying algorithms, but it's up to you.

Meanwhile I'll add a CC0 license to make my intent clear.

**Comment by yoanlcq** [comment]
Closed by latest commits. Feel free to reopen for further discussion.
